catch 와 throw 차이점
catch
	예외를 처리하는데 사용되는 키워드
	try-catch 블록 내부에 사용되며, 예외가 발생할 가능성이 있는 코드를 try 블록 내 포함시킨다.
	예외가 발생하면 catch 블록 내에 코드가 실행되고 해당 예외를 처리하는 로직을 구현할 수 있다.
	catch 블록은 예외의 타입과 일치하는 예외 핸들러를 찾아 실행한다.
	여러개의 catch 블록이 중첩될 수 있다.
	
throw
	예외를 발생시키는데 사용되는 키워드
	예외를 발생시키면 예외 객체가 생성된다.
	예외가 발생한 시점에서 프로그램 실행 중단
	메서드에서 직접 처리되지 않을 경우 호출 스택을 따라 상위 호출 스택으로 전파
	예외적인 상황을 나타내고 예외를 처리하는 부분으로 제어를 전달
	
catch는 예외를 전달, throw는 아예 버리는것